### ISSUE TITLE
We need a Doctoral Symposium page

### ISSUE THREAD

**Issue by mmcdermott** [acm-chil/acm-chil-website#9] opened 2020-07-07 15:08 UTC
I think we can model this page precisely off of the Tutorial page, with the "titles" of tutorials replaced by the DS participant names, and short blurbs provided per participant based on their submitted thesis summaries. If this is doable, what's the best way for me to provide the relevant info (participant names and blurbs). Eventually, we'll add the slideslive video links to this page too, ideally.

The caveats to this are (1) I'll be crafting these blurbs, based on their thesis summaries, so they may change as I'll likely make drafts that we can post, then send them out to participants to confirm, and (2) it still isn't clear if everyone from the DS is still participating. I'm not sure when we'll get finalization from that, other than in seeing who has submitted talks by July 11. Point being, we'll likely need to update this content later on, though I hope/presume that this won't be an issue.

**Comment by tnaumann** [comment] 2020-07-07 15:13
@mmcdermott Can you merge this with Issue #6 re: adding a tab for DS?

**Comment by mmcdermott** [comment] 2020-07-07 15:18
Looks like we'll need to make a CSV like this: https://github.com/acm-chil/acm-chil-website/blob/master/sitedata/workshops.csv and   make a copy of a page like this: https://github.com/acm-chil/acm-chil-website/blob/master/templates/workshops.html for tutorials, then add something somewhere to ensure things are routed properly and another tab shows up. Is that about right, @tompollard? If so, is the csv from me the main thing you need?

**Comment by corcra** [comment] 2020-07-07 16:54
@mmcdermott It's fairly easy to make a duplicate of the workshops page/functionality, so if you can provide the CSV I can add that.

**Comment by tompollard** [comment] 2020-07-07 18:47
@mmcdermott the doctoral symposium content can now be added to https://github.com/acm-chil/acm-chil-website/blob/master/sitedata/dss.csv (thanks stephanie!)

**Comment by mmcdermott** [comment] 2020-07-10 14:03
Updating here that I have all the content drafted, but plan to reach out to the authors first to confirm they are comfortable with our given abstracts for them, and will plan to push the final content of the page early next week.

**Comment by mmcdermott** [comment] 2020-07-10 14:14
@tompollard @corcra are there any length restrictions to keep in mind for the "abstract" column on this page? Also, echoing Tom's thanks for the DS page template!

**Comment by tompollard** [comment] 2020-07-10 14:29
@mmcdermott no real limitation as far as I'm aware, but it would be nice for the content to be reasonably consistent. perhaps ask for max ~250 words and don't worry too much if people go over?

**Comment by tnaumann** [comment] 2020-07-17 03:09
@mmcdermott I've updated https://github.com/acm-chil/acm-chil-website/blob/master/sitedata/dss.csv to include basic information as part of incorporating SlidesLive ID for each. Would be good to get title/abstract added though.

**Comment by mghassem** [comment] 2020-07-17 04:07
@tompollard Can you move the Keynotes and Tutorials tabs to be their own tabs in the top menu along with Doctoral Symposium?

That way the Schedule tab can only have: 
    Guidance
    Pre-recorded Content
    Thursday Schedule
    Friday Schedule

**Comment by mmcdermott** [comment] 2020-07-17 15:05
Thanks @tnaumann - I've added the titles and abstracts that we were collating from attendees. My changes are in the branch [`DSS_data`](https://github.com/acm-chil/acm-chil-website/tree/DSS_Data). @corcra do you want to add the template page (using the CSV in that branch) and we can push it all to master?

**Comment by tompollard** [comment] 2020-07-17 15:40
@mghassem for this particular issue and pull request, I'd suggest keeping the tabs in the current locations (i.e. doctoral symposium on the 2nd level, under schedule).

The way the content is organized means moving tabs isn't trivial, so perhaps this can go into a new issue after the doctoral symposium content is merged and then we can have a play around.

The top level menu doesn't handle a large number of items very well (the formatting gets screwy), so rearranging the menu items needs some thought.

**Comment by corcra** [comment] 2020-07-19 18:14
@mmcdermott I've updated `DSS_data` branch with the required edit - there should now be an additional tab under schedule with the doctoral symposium info

**Comment by corcra** [comment] 2020-07-19 18:15
The edit I made will also make it easier to add a tab for workshops once we have a corresponding csv file (#8)

**Comment by mmcdermott** [comment] 2020-07-20 00:28
Great, thanks, @corcra! I don't see it on the live site - does something still need to pushed?

**Comment by corcra** [comment] 2020-07-20 10:51
Sorry @mmcdermott, wasn't sure if you wanted to review it in the branch before deploying - I've merged + deployed it now, let me know if anything looks off but I'll close this issue for now.

**Closed by corcra** 2020-07-20 10:51 UTC
